### ISSUE TITLE
Think of implementing some grammar-based architecture generator

### ISSUE THREAD

**Issue by kabbi** [Terasology/Cities#20]
There is a guy out there, who implements some commercial real-time voxel renderer software. And he has pretty decent implementation of l-system grammar to make buildings.
His blog with examples here:
http://procworld.blogspot.com.by/search/label/Grammar.

If someone has already declined the idea, I say sorry. But if not, I think it would be pretty challenging to implement something like this for city generator.

I offer my candidature for actually trying to implement this, although I have pretty little experience with formal grammars and procedural content generation.

**Comment by Cervator** [comment]
Good timing! Not only do we like this idea, we've already worked a little on it in the past, or more specifically @skaldarnar has over at https://github.com/Terasology/GrammarSystem and https://github.com/skaldarnar/PAG

Both of those are a fair bit dated by now but should prove some good review material. And on top of that @skaldarnar *just* ended up with a bit of free time and started clearing out the dust a bit. He was working with another grammar-interested dev last time around so I'm sure he'd love the chance to discuss ideas and implementation again :-)

**Comment by skaldarnar** [comment]
Hey @kabbi, I'm reading the blog for some time now, I think that was one of my initial sources to get started - along with all the scientific papers available on the topic. 
I started to play around with a Scala-based implementation of the grammar system, just for the fun of it. Where I left off in the old system was the implementation of different *shapes* and how to handle transformations, such as rotations and scaling. In the end, some kind of *rasterization* is needed to turn the grammar shapes into blocks... 
I would be happy to hear your thoughts on this, it would be great if we could coordinate to work together on this as I think working out a grammar system becomes more usable if there's a second pair of eyes having a look at it.

**Comment by Cervator** [comment]
Yeah grammar in particular probably needs more eyes - that stuff can get confusing :D

**Comment by kabbi** [comment]
Ok, let me have several days (or even a week) to look through all the papers, your modules and source code (I really want to play with it, if it compiles ok), and I'll post my ideas here. Or is there some better place for such discussions?
Anyway, thank you for your fast response!

**Comment by skaldarnar** [comment]
Better places for general discussion would be the IRC chat or the [forums](http://forum.terasology.org/forum/). I'd like to keep GitHub for discussion source code, e.g., pull requests or some gist snippets. 

I'm pretty sure the old module won't compile atm, there were quite a lot changes to the code base of the game since it last worked. I'll try to see what I can do about that, although I'm not sure if it will run at the end of the week or not …

**Comment by Cervator** [comment]
Specifically in this thread :-)

http://forum.terasology.org/threads/procedural-architecture-grammar.586/

And sorta related (more papers!) - http://forum.terasology.org/threads/gsoc-city-generation-and-sensible-land-usage.974

I'll close this issue for now to let discussion continue in the forum, it'll be a while before any code gets to a point where we can integrate with Cities I imagine :D
